### GENERAL SETTINGS ###
safe: true
future: true

# Site settings
title: ITed Services
tagline: "It's all about the learning"
description: "ITed Services is a education IT solutions company based in Tauranga, NZ. We are a talented and passionate team that is committed to helping your school get the best use out of your ICT."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.ited.co.nz"

paginate: 5
paginate_path: /blog/:num/

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#b22222" #F70031
  primary_rgb: "178,34,34" # "247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#000000" #384452
  link: "#b22222"
  link_hover: "#000000"
  footer_heading: "#ffffff"
  footer_content: "#ffffff" #bfc9d3
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: support
    url: https://ited.zendesk.com/hc
  - title: facebook
    url: https://www.facebook.com/itedservices
  - title: twitter
    url: https://www.twitter.com/itedservices
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 15 Minden Road,
    - RD 6,
    - Te Puna, Tauranga
email: hello@ited.co.nz
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Kelvin Maine
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kelvin@ited.co.nz
      - title: twitter
        url: http://twitter.com/kbjmaine
  - name: Kees Fransen
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kees@ited.co.nz
      - title: twitter
        url: http://twitter.com/keesfransen
  - name: Richard van Dijk
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:richard@ited.co.nz
      - title: twitter
        url: http://twitter.com/rbvandijk
    
# Clients information. Shown on Home and About pages.
clients:
  - name: Mount Maunganui College
    img: mmc-bw.png
    link: http://www.mmc.school.nz/
  - name: Omokoroa Point School
    img: omok-bw.png
    link: http://www.omokoroapoint.school.nz/
  - name: Papamoa College
    img: papamoa-bw.png
    link: http://www.papamoacollege.school.nz
  - name: Katikati College
    img: kkc-bw.png
    link: http://www.kkc.school.nz
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We believe in building relationships with our schools because if we have an understanding of what your vision is we can help to clarify, identify the challenges and the steps to take and refine it into something tangible."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Thanks again for your support. I will test the qtypes-formulas question later today. As said before, we've been waiting for four years to get action on this add-inn so you get hero status."
    author: Ken Ben
    position: PNBHS - Stratus
